apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui-app
  template:
    metadata:
      labels:
        app: ui-app
    spec:
      containers:
      - name: ui-app
        image: python:3.11-slim
        command: ["python3", "-m", "http.server", "80"]
        workingDir: /usr/src/app
        ports:
        - containerPort: 80
        volumeMounts:
        - name: ui-static-volume
          mountPath: /usr/src/app
      volumes:
      - name: ui-static-volume
        configMap:
          name: ui-static
          items:
          - key: index.html
            path: index.html
