apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
spec:
  project: default
  source:
    chart: nats
    repoURL: https://nats-io.github.io/k8s/helm/charts/
    targetRevision: 1.2.11
    helm:
      values: |
        config:
          jetstream:
            enabled: true
        # The main server container resources
        nats:
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        # The reloader sidecar (OPA sees this too!)
        reloader:
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
        # The nats-box tool
        natsBox:
          enabled: true
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: nats-io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false
