apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: websocket-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nishchay16/k3s-gitops-assignment.git
    targetRevision: main
    path: apps/websocket
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
